# Generated by Django 4.1.2 on 2022-10-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='name',
        ),
    ]
