# Generated by Django 4.1.2 on 2022-10-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
        ('users', '0004_person_person_type_person_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_id',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialties.classe'),
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
