# Generated by Django 4.1.2 on 2022-11-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_subject_class_id_alter_studentprofile_classe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher')], default='ST', max_length=2),
        ),
    ]
