# Generated by Django 4.1.2 on 2022-10-31 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stackQA.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stackQA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=stackQA.models.Answer, to='stackQA.question')),
            ],
        ),
    ]
